
import Cookies from 'universal-cookie'
import React, { useState, useEffect, Component } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import AsyncSelect from 'react-select/async';
import dynamic from 'next/dynamic'
import axios from 'axios';




// MAIN HTML GENERATING FUNCTION
export default function example({ data,data1,data_id1 }) {
    const [email, setEmail] = useState('')
  const [comment, setComment] = useState('')
  const [nagrada, setNagrada] = useState('')
  const [soba, setSoba] = useState('')
  const [opis, setOpis] = useState('')
  const [zacetek, setZacetek] = useState('')
  const [davek, setDavek] = useState('')
  const [picture, setPicture] = useState('')
  const [money, setMoney] = useState('')
  const cookies = new Cookies();
  
  const game_id = data_id1;

  
  async function handleRegister(event){
    window.open('/login',"_self");
}
  const isLogged = cookies.get('userLogged');

    const submit = e => {
        e.preventDefault()
        
        axios.get(`http://localhost:3000/register?email=${email}&picture=${picture}&comment=${comment}&nagrada=${nagrada}&soba=${soba}zacetek=${zacetek}&opis=${opis}&davek=${davek}&money=${money}`);
       

      }  
 
  return (
    
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 id="demo" className="text-7xl bg-white text-white p-5 pb-7 rounded-lg">
        Get easy money with pay 2 win.
        </h1>

    <div>
    <h1>IZPOLNITE PROSIM</h1>
    <div class="border-double border-4 border-indigo-600 px-6 py-6 rounded-lg">
    <form onSubmit={submit}>
      
      <br />
      <label htmlFor="nagrada">Username:</label><br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="nagrada"
        value={nagrada}
        onChange={e => setNagrada(e.target.value)}
        /><br />
      <br />
      
      <label htmlFor="opis" >Password:</label><br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="opis"
        value={opis}
        onChange={e => setOpis(e.target.value)}
        /><br />
      <br />

      <label htmlFor="soba">Email:</label><br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="soba"
        value={soba}
        onChange={e => setSoba(e.target.value)}
        /><br />
      <br />

      <label htmlFor="zacetek">Name:</label> <br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="zacetek"
        value={zacetek}
        onChange={e => setZacetek(e.target.value)}
        /><br />
      <br />

      <label htmlFor="davek">Surname:</label> <br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="davek"
        value={davek}
        onChange={e => setDavek(e.target.value)}
        /><br />
      <br />
   
      
      <label htmlFor="email">Taxnumber:</label> <br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="email"
        value={email}
        onChange={e => setEmail(e.target.value)}
        /><br />
      <br />

      <label htmlFor="comment">Phone:</label> <br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="comment"
        value={comment}
        onChange={e => setComment(e.target.value)}
        /><br />
      <br />

      <label htmlFor="money">Money:</label> <br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="money"
        value={money}
        onChange={e => setMoney(e.target.value)}
        /><br />
      <br />

      <label htmlFor="picture">Picture:</label> <br />
      <textarea rows="1" cols="50" style={{border: '2px solid black'}}
        name="picture"
        value={picture}
        onChange={e => setPicture(e.target.value)}
        /><br />
      <br />
      <br />

      <br />
      
      <button  type="submit" class="p-4 bg-blue-700 hover:bg-blue-500 w-50 rounded-lg shadow text-xl font-medium uppercase text-white"  type="button"
                    onClick={handleRegister}
  >  Submit!  </button><br />
    </form>
    
    </div>
    </div>    

      </main>

    </div>
  )      
} 





//DATA FETCHING FROM WEBSERVER (copy when need data from apy)
export async function getStaticProps(context) {
  const res = await fetch(`http://localhost:3000/games`)
  const data = await res.json()
  const res1 = await fetch(`http://localhost:3000/tourtaments`)
  const data1 = await res1.json()
  const res2 = await fetch(`http://localhost:3000/forma`)
   const data_id = await res2.json()

  
  console.log(data)
  
  if (!data) {
    return {
      notFound: true,
    }
  
  }
  console.log(data1)
  console.log(data_id[0].id)
  let x=parseInt(data_id[0].id)
  x=x+1;

  const data_id1=String(x);
  console.log(data_id1)
  return {
    props: { data,data1,data_id1 }, // will be passed to the page component as props
  }
}

